services:
  - type: web
    name: sia2-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: your-db-name
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        value: your-db-password
